services:
  - type: web
    name: home-smart-storage
    runtime: node
    plan: free
    buildCommand: cd client && npm install && npx vite build && cd ../server && npm install
    startCommand: node start.js
    envVars:
      - key: NODE_ENV
        value: production
